services:
  app:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src
    working_dir: /src
    command: sh -c "npm install && npm update && npm run dev"
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
