services:
  app:
    image: node:24.2-slim
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=production
    working_dir: /app
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
      - next:/app/.next
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm update && npm run build && npm run start"

volumes:
  node_modules:
  next:
